name: Deploy to GitHub Pages

on:
  push:
    branches: [ project-analysis ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      
    - name: Create basic site
      run: |
        mkdir site
        echo "<!DOCTYPE html><html><head><title>100networks.com</title></head><body><h1>🎉 100networks.com is LIVE!</h1><p>Domain successfully configured</p><a href='http://13.62.13.0:3000'>View Full App</a></body></html>" > site/index.html
        echo "100networks.com" > site/CNAME
        
    - name: Upload to GitHub Pages
      uses: actions/upload-pages-artifact@v3
      with:
        path: site
        
    - name: Deploy to GitHub Pages
      uses: actions/deploy-pages@v4
      id: deployment
      with:
        token: ${{ github.token }} 